### PR TITLE
Phaser 2.3 Compatibility

### PR DESCRIPTION
**Pull request by mfpierre**
Make the plugin compatible with Phaser 2.3: No _cache object anymore.

https://github.com/photonstorm/phaser/commit/8483eac6aac7e325e528af8893ac4f5b2beb512e

### CODE REVIEW

**Comment by lewster32** [comment]
:+1:

**Comment by LunarDevelopment** [comment]
I'm using phaser v2.3 and I'm getting the following error when trying to implement the website homepage example: 

```
Uncaught TypeError: Cannot read property '4' of undefined
``` 
Coming from the plugin 
```javascript
this.sprite._cache[4]
```
Is the problem that the example for the home page of your site uses the old phaser or am I dont something wrong.. ?

**Comment by mfpierre** [comment]
The homepage of the site is using v0.9.1 you should use v0.9.2 which contains the following fix for phaser 2.3

**Comment by LunarDevelopment** [comment]
Thanks for clearing that up. It turns out Bower install returns v0.9.0 

I'll update my files!

**Comment by LunarDevelopment** [comment]
Ola, 

Sorry to be a pain, and I really appreciate the help I keep receiving, but I'm still having problems with this. 

Phaser v 2.3
Iso v.0.9.2 

```sh 
Uncaught TypeError: Cannot read property '4' of undefined 
```
```javascript 
      var myself = this;
      
      //  A more suitable underwater background color
      myself.game.stage.backgroundColor = '#1873CE';
      // Create a group for our tiles.
      isoGroup = myself.game.add.group();
      // Set the global gravity for IsoArcade.
      myself.game.physics.isoArcade.gravity.setTo(0, 0, -500);
      // we won't really be using IsoArcade physics, but I've enabled it anyway so the debug bodies can be seen
      isoGroup.enableBody = true;
      isoGroup.physicsBodyType = Phaser.Plugin.Isometric.ISOARCADE;
```

**Comment by mfpierre** [comment]
There is an issue with the minified file, try this one instead https://github.com/lewster32/phaser-plugin-isometric/blob/master/dist/phaser-plugin-isometric.js

I've made a PR to fix it :)

**Pull request merged**
